### ISSUE TITLE
Personen denen die Karten freigegeben wurden können teilweise sehen wem das noch freigegeben wurde

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#10]
-	Personen denen die Karten freigegeben wurden können teilweise sehen wem das noch freigegeben wurde --> kann ich nicht immer reproduzieren

**Comment by luniki** [comment]
Kann ich auch nicht reproduzieren.

**Comment by luniki** [comment]
Kann ich doch reproduzieren und hab ich behoben.
