### ISSUE TITLE
Freigegebene Karten sind auf einer Hierachieebene mit Ordnern

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#11]
-	Freigegebene Karten sind auf einer Hierachieebene mit Ordnern - das ist sehr unerwartet

**Comment by luniki** [comment]
Ja, das war so geplant. Es darf auch Kartensätze ohne Ordner geben. Insofern ist das nicht wirklich ein Fehler.

**Comment by alinastolzenburg** [comment]
ich habe eine Lösung in #35 beschrieben
