### ISSUE TITLE
Lernkarten ohne Ordner

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#15]
-	Ich kann Lernkarten ohne Ordner nicht im Nachhinein in Ordner packen  Chaos
- > das würde auch #11 helfen

**Comment by luniki** [comment]
Wenn ich einen Kartensatz bearbeite, kann ich dort den Ordner angeben und ändern.
![Selection_077](https://github.com/elan-ev/studip-lernkarten/assets/2993/be75ada7-468e-47b8-972a-5a020d47125f)
