### ISSUE TITLE
Urheberrechtsprobleme

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#16]
-	Bei Kopierten Karten werden die Personen mit denen der Kartensatz geteilt wurde zu „ersteller:innen“ (siehe „erstellt von“) Sobald man diesen Kartensatz nochmal kopiert gehen die ursprünglichen ersteller:innen komplett verloren

**Comment by luniki** [comment]
Die ursprünglichen Erstellenden können in den Metadaten ausgedrückt werden.

Statt "erstellt von" müsste dort der "Besitz" dieses Kartensatzes ausgedrückt werden. Hast du eine gute Idee, wie wir da das Wording ändern können?

Technisch gesehen ist diese Person ein "owner" und hat komplette Bearbeitungsrechte.

**Comment by luniki** [comment]
Ich hab das Problem jetzt ein wenig entschärft. Demnächst werden bei Kartensätzen, die ich nur "mitlerne", der Teilende als Owner angezeigt. Das dürfte an der Stelle schon einmal helfen.

Bei kopierten Kartensätzen halte ich das für korrekt, dort mich als Owner zu sehen und nicht den Teilenden. Es gibt kein Kriterium, das festlegt, wann ich oder die Teilenden die Owner sind. Ich selbst hab Bearbeitungsrechte und bin an der Stelle definitiv Owner.

Gut wäre allerdings, wenn wir statt "erstellt von" einen besseren Begriff finden, der eher das "Ich kann diesen Kartensatz gestalten." ausdrückt. Das Teilen von Kartensätzen hebt das ganze Konzept von Ersteller*innen auf.

Findest du da eine gute Formulierung?

**Comment by alinastolzenburg** [comment]
das finde ich dadurch schon deutlich besser! Ich würde vorschlagen dass bei kopierten Kartensätzen immer auch die person von der man kopiert hat auch unter den Erstellenden auftaucht? Ansonsten wäre "bearbeitet durch" vielleicht eine Option und dann den die ursprünglich erstellende in den Metadaten aufführen?

**Comment by luniki** [comment]
Ja, dann vermerke ich dort die Person als "bearbeitet durch". Alles andere muss dann in die Metadaten.

**Comment by luniki** [comment]
Ist dann in der nächsten Version behoben.
