### ISSUE TITLE
Auf der Startseite wird beim „Kartensatz lernen“ nur ein Kartensatz ausgewählt

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#17]
diesen kann ich auch nicht verändern (ich würde erwarten alle kartensätze zu lernen)

**Comment by luniki** [comment]
Das kann ich nicht nachvollziehen.

Bedeutet "Startseite" den Reiter "Lernkarten" im Arbeitsplatz?

Wenn ja, hab ich passende Screenshots.

### Mehrere Kartensätze auf der Startseite
![Mehrere Kartensätze auf der Startseite](https://github.com/elan-ev/studip-lernkarten/assets/2993/333d221e-3bef-4bf1-9068-b127e6bda2a8)

### "Kartensätze lernen" drücken
![Screenshot 2023-12-20 at 12-57-53 LernkartenPlugin - Stud IP](https://github.com/elan-ev/studip-lernkarten/assets/2993/a5221347-99a6-432b-9753-150cb2c677a0)

### Alle Karten wurden geladen
![Screenshot 2023-12-20 at 12-58-01 LernkartenPlugin - Stud IP](https://github.com/elan-ev/studip-lernkarten/assets/2993/8a01ea8d-f791-46af-a941-df7a9a05c09d)

**Comment by alinastolzenburg** [comment]
![image](https://github.com/elan-ev/studip-lernkarten/assets/116811905/e642058e-0033-4120-841c-1a243793775e)

**Comment by alinastolzenburg** [comment]
sieht für mich so aus als würden die Kartensätze ohne ornder gelernt (obwohl der knopf unter den Ordnern ist?)

**Comment by luniki** [comment]
Hmm, jetzt verstehe ich dieses Issue besser.

Tatsächlich sollen mit diesem Knopf alle Kartensätze gelernt werden, die sich auf der aktuellen Ordnerebene befinden. In deinem Fall also der eine Kartensatz, der unten angezeigt wird. Das müssen wir dann optisch noch einmal anpassen, um das klarer zu machen. Vielleicht kommt der Punkt am besten in die Sidebar?

**Comment by luniki** [comment]
Ich habe jetzt den Punkt in die Sidebar verschoben. In der nächsten Version ist das also behoben.
