### ISSUE TITLE
Lernkarten Teilen - keine Info dass in der Veranstaltung das Plugin angeschaltet sein muss

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#18]
-	Lernkarten Teilen --> Es gibt keine Info dass in der Veranstaltung das Plugin angeschaltet sein muss so bekomme ich einfach keine Veranstaltungen zur Auswahl das ist sehr verwirrend

**Comment by luniki** [comment]
Wird behoben
