### ISSUE TITLE
Plugin hat keine Beschreibung (auf der Seite „Mehr…“)

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#19]

**Comment by luniki** [comment]
Pflege ich gerne ein. Welcher Text ist geeignet?

**Comment by alinastolzenburg** [comment]
Vorschlag von Johanna und mir: 
Lernkarten sind digitale Karteikarten, die beim Wiederholen von Lerninhalten unterstützen können. Die einzelnen Lernkarten können sowohl Bilder als auch Text enthalten. Lernende können Ihren eigenen Fortschritt in der Lernstatistik überprüfen
Lehrende und Studierende können in ihrem Arbeitsplatz beliebig viele Kartensätze anlegen. Als Lehrende können Sie diese in eine Stud.IP-Veranstaltung integrieren und den Teilnehmenden zur Verfügung stellen.
Die Kartensätze können „mitgelernt“ werden. Ist diese Funktion aktiviert, erhalten „Mitlernende“ regelmäßig Updates, wenn die erstellende Person neue Karten hinzufügt.“ Zusätzlich besteht die Option, sich einen Kartensatz zu „kopieren“. Wenn Lernende diese Funktion nutzen, übernehmen sie den Kartensatz in ihren Arbeitsplatz und können ihn selbst weiter gestalten. 
In Courseware gibt es ab sofort den neuen „Lernkarten“-Block, über den Lernkarten direkt in ein Lernmaterial integriert werden können, um so zum Beispiel Selbsttests für Studierende zu gestalten.

**Comment by luniki** [comment]
Ich nehme das für die lange Version des Plugins. Was wäre die kurze Beschreibung?

**Comment by alinastolzenburg** [comment]
wie kurz ist kurz? Hast du da Vorgaben für mich?

**Comment by luniki** [comment]
Das ist das, was auf der "Mehr"-Seite angezeigt wird. Zum Beispiel für Courseware: "Lerninhalte erstellen, verteilen und erleben"

**Comment by alinastolzenburg** [comment]
Lernkarten: Digitale Karteikarten erstellen, austauschen und lernen.

**Comment by luniki** [comment]
Ist in der nächsten Version erledigt.
