### ISSUE TITLE
Mitlernen/ Kopieren wird nicht verstanden

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#21]
-	Mitlernen/ Kopieren wird nicht verstanden (und wie man das aktiviert dementsprechend auch nicht) 
- --> bestenfalls finden wir hier noch eine Lösung direkt im Plugin?

**Comment by luniki** [comment]
Wie schon besprochen, sind wir hier auf konkretet Änderungsvorschläge angewiesen.

**Comment by alinastolzenburg** [comment]
- Dialogfenster "mitlernen" (idealerweise: "verknüpfen") modifizieren: Wenn Sie den Kartensatz mitlernen, haben sie keine Möglichkeit, die darin enthaltenen Karten zu bearbeiten. WENN DIE ERSTELLENDE PERSON NEUE KARTEN ERSTELLT, WIRD DER MIT IHNEN GETEILTE KARTENSATZ AKTUALISIERT.

- Dialogfenster "Kopieren" modifizieren: Wenn Sie den Kartensatz kopieren, können Sie diesen und die darin enthaltenen Karten beliebig bearbeiten. IHR KARTENSATZ WIRD ALLERDINGS NICHT AKTUALISIERT, SOLLTE DIE ERSTELLENDE PERSON NEUE KARTEN HINZUFÜGEN.

- "Mitlernen" braucht ein anderes Symbol (zB "Verknüpfen"-Symbol). 

- Zur besseren Verständlichkeit könnten die Begriffe "verknüpfen" und "kopieren" genutzt werden. Auf diese Weise würden gängige Termini integriert, wodurch die Abgrenzung zwischen beiden Optionen verständlicher wird und die Konsistenz im System gewährleistet ist.

- Anforderung: Für Nutzende wäre es sinnvoll, wenn sie die zwei möglichen Optionen (mitlernen vs. kopieren) auf einen Blick sehen können. Hierzu sollte im Idealfall beim Betreten des Arbeitsplatzes ein Dialog aufploppen, sobald ein neuer Kartensatz mit Ihenen geteilt wurde. "Nutzer:in xy hat einen neuen Kartensatz mit Ihnen geteilt möchten Sie diesen "verknüpfen" oder sich eine "Kopie" des Katensatz speichern" --> zwei Knöpfe. Wird dieser Dialog geschlossen sind die zwei knöpfe nebeneinander am Kartensatz zu finden.
