### ISSUE TITLE
Geteilte Kartensätze können nach belieben weiter verbreitet werden

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#25]
-	Aktuell kann ich einen Kartensatz teilen aber das Kopieren nicht unterbinden. Sobald kopiert wurde kann der kartensatz nach belieben weiter verbreitet werden - das sehe ich als Erstellerin noch nicht einmal und ich werde als erstellerin auch nicht mehr aufgeführt siehe #16

**Comment by luniki** [comment]
Laut Anforderungsdokument verhält sich das wie gefordert.

Was wäre das eigentlich gewünschte Verhalten?

**Comment by alinastolzenburg** [comment]
Ja da hast du recht - ich denke soweit hatten wir noch nicht gedacht. Minimal muss der Name der Ersteller:in unlöschbar in den Metadaten sein. Bestenfalls kann ich beim Teilen einstellen ob ich nur mitlernen oder auch kopieren erlauben will (und was das bedeutet)

**Comment by luniki** [comment]
Okay. Das müssen wir genauer spezifizieren.

**Comment by alinastolzenburg** [comment]
Zukünftig wäre es wünschenswert beim Teilen zwei optionen zu erhalten - andere Person darf mitlernen oder sich eine kopie ziehen. Für jetzt ist es so wie es ist (wenn die Urheberrechtsproblematik gelöst ist) erstmal ok.
