### ISSUE TITLE
Mobilansicht: Lernstatistik Dialog nicht richtig formatiert

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#26]
Mobilansicht 
-	Lernstatistik Dialog nicht richtig formatiert (wenn nicht alle karten gelernt wurden)

**Comment by luniki** [comment]
Ich brauch hier noch einmal Feedback. Kannst du mir einen Screenshot davon anfertigen?

**Comment by alinastolzenburg** [comment]
![Screenshot_20240208_130340_Chrome](https://github.com/elan-ev/studip-lernkarten/assets/116811905/1fd1e960-ccb1-4dcf-b1aa-f035433ef260)
![811834cc-2d6f-43f7-8d14-95ea34bf6b76](https://github.com/elan-ev/studip-lernkarten/assets/116811905/89f54aaa-6322-4dfa-9378-3e91b28a94ad)

**Comment by luniki** [comment]
In v1.1.0 behoben
