### ISSUE TITLE
Mobilansicht: es lassen sich keine Karten anlegen

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#28]
-	In der Mobilansicht lassen sich keine Karten anlegen (Aktionen sind nicht da)

**Comment by luniki** [comment]
Ich habe das in der aktuellen Version ausprobiert. Dort scheint das besser zu funktionieren.
![Uploading Screenshot 2024-02-07 at 12-02-07 LernkartenPlugin - Stud.IP.png…]()

**Comment by luniki** [comment]
Ich schließe dieses Issue erst einmal, weil ich davon ausgehe, dass das behoben ist.
