### ISSUE TITLE
Courseware: Lehrende sollten im Lesemodus auch die Sicht der Lernenden haben

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#29]
Ich hätte hier erwartet direkt in der CW lernen zu können

**Comment by luniki** [comment]
Das verstehe ich nicht so richtig. Kannst du das genauer zeigen? Eigentlich sollte das dort direkt lernbar sein.

**Comment by alinastolzenburg** [comment]
![image](https://github.com/elan-ev/studip-lernkarten/assets/116811905/7d9edd4f-03e5-449b-8337-2debb3c6caf0)
So sieht das bei mir aus. Wenn ich auf dem Link klicke lande ich im Lernkarten Plugin

**Comment by luniki** [comment]
Ist das die Lehrendensicht? Die unterscheidet sich von der Lernendensicht.

**Comment by alinastolzenburg** [comment]
ja das ist die lehrendensicht. Allerdings ist das sehr unerwartet für Lehrende. In der Regel wird in der Ansicht "Lesen" das gezeigt was auch die Studis sehen so ist es nicht nachvollziehnbar für lehrende das Studis direkt in der CW Lernen können.

**Comment by luniki** [comment]
Okay, das werde ich beheben.
