### ISSUE TITLE
Darstellung des Fortschritts

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#3]
Fortschritt - Darstellung  ist nicht so wie die Balken bei den Karten (Statistik?) selbst – gleiche Farben und Co als Tortendiagramm wären gut

**Comment by luniki** [comment]
Tortendiagramme sind generell verpönt. Siehe zB: https://home.uni-leipzig.de/methodenportal/grafiken-2/
