### ISSUE TITLE
Geteilte Kartensätze in Ordner verschieben

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#35]
Karten in Ordner verschieben:
Wenn ich im Arbeitsplatz die Lernkarten nutze und von anderen Nutzer:innen Karten "bekomme", gibt es aktuell keine Möglichkeit, diese in einen Ordner zu verschieben. Ich habe also keine Möglichkeit, meine Kartensätze zu sortieren - wozu gibt es dann überhaupt Ordner?
Das sollte hier funktionieren wie im Dateibereich.

**Comment by luniki** [comment]
Du meinst mit mir geteilte Kartensätze?

**Comment by alinastolzenburg** [comment]
ja (sorry)

**Comment by luniki** [comment]
Da benötigen wir ein anderes Konzept. Im Moment ist das einfach nicht möglich.

**Comment by luniki** [comment]
Behoben in 78228fe300b1992e84fa12ffb07d4fc012593749
