### ISSUE TITLE
Geteilte Kartensätze lassen sich lernen ohne dass sich für "kopieren" oder "mitlernen" entschieden wurde 

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#36]
Wenn mit mir ein Kartensatz geteilt wurde, habe ich im Arbeitsplatz unmittelbar die Möglichkeit, auf diesen Kartensatz zu klicken. Über diesen Klick gelange ich direkt zum Kartensatz und kann direkt "Lernen" - auch ohne, dass ich vorher entschieden habe, ob ich den Kartensatz mitlernen oder kopieren will.

**Comment by luniki** [comment]
Das wird in der nächsten Version behoben sein.
