### ISSUE TITLE
Kartensatz Löschen Dialog

### ISSUE THREAD

**Issue by alinastolzenburg** [elan-ev/studip-lernkarten#7]
![image](https://github.com/elan-ev/studip-lernkarten/assets/116811905/3b503715-3ce1-485a-bb97-4e637a68d48f)
 
Komisch formatiert

**Comment by luniki** [comment]
Das stimmt. Ich verwende hier den Standard-Vue-Dialog für die Bestätigung. Dort ist das leider ganz normal. Ich melde mal im Stud.IP-Kern ein BIEST dazu.
